.PHONY: clean-pyc clean-build docs clean

help:
	@echo "clean-pyc - remove Python file artifacts"


clean-pyc:
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	find . -name '__pycache__' -exec rm -fr {} +
